title: More of Jesus Less of Me
author: reneedowns
email: us@morejesuslessme.com
description: > # this means to ignore newlines until "show_exerpts:"
  Renee Galle's blog about her family and Jesus
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  #name: He must increase,</br>but I must decrease 

  tagline: He must increase,</br>but I must decrease</br>- John 3:30
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  # generate social links in footer
  social_links:
    #twitter: thelehhman
    #github:  thelehhman
    #linkedIn: in/thelehhman
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#- about.md

# Build settings
#theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
